INSERT INTO services (id, username, url, script, callback) VALUES (1, 'Visualizza home', '/', 'home.php', 'home');
INSERT INTO services (id, username, url, script, callback) VALUES (2, 'Visualizza about', '/about', 'about.php', 'about');
INSERT INTO services (id, username, url, script, callback) VALUES (3, 'Visualizza contact', '/contacts', 'contacts.php', 'contacts');
INSERT INTO services (id, username, url, script, callback) VALUES (4, 'Visualizza login', '/login', 'access.php', 'login');
INSERT INTO services (id, username, url, script, callback) VALUES (5, 'Effettua logout', '/logout', 'access.php', 'logout');
INSERT INTO services (id, username, url, script, callback) VALUES (6, 'Visualizza carrello', '/cart', 'cart.php', 'cart');
INSERT INTO services (id, username, url, script, callback) VALUES (7, 'Visualizza home admin', '/admin', 'admin/index.php', 'admin');
INSERT INTO services (id, username, url, script, callback) VALUES (8, 'Visualizza ordini', '/admin/orders', 'admin/orders.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (9, 'Visualizza singolo ordine', '/admin/orders/%', 'admin/orders.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (10, 'Modifica ordine', '/admin/orders/%/edit', 'admin/orders.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (11, 'Cancella ordine', '/admin/orders/%/delete', 'admin/orders.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (12, 'Visualizza utenti', '/admin/users', 'admin/users.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (13, 'Visualizza singolo utente', '/admin/users/%', 'admin/users.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (14, 'Modifica utente', '/admin/users/%/edit', 'admin/users.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (15, 'Cancella utente', '/admin/users/%/delete', 'admin/users.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (16, 'Visualizza prodotti', '/admin/products', 'admin/products.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (17, 'Visualizza singolo prodotto', '/admin/products/%', 'admin/products.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (18, 'Modifica prodotto', '/admin/products/%/edit', 'admin/products.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (19, 'Cancella prodotto', '/admin/products/%/delete', 'admin/products.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (20, 'Visualizza categorie', '/admin/categories', 'admin/categories.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (21, 'Visualizza singola categoria', '/admin/categories/%', 'admin/categories.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (22, 'Modifica categoria', '/admin/categories/%/edit', 'admin/categories.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (23, 'Cancella categoria', '/admin/categories/%/delete', 'admin/categories.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (24, 'Visualizza produttori', '/admin/producers', 'admin/producers.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (25, 'Visualizza singolo produttore', '/admin/producers/%', 'admin/producers.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (26, 'Modifica produttore', '/admin/producers/%/edit', 'admin/producers.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (27, 'Cancella produttore', '/admin/producers/%/delete', 'admin/producers.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (28, 'Visualizza provenienze', '/admin/provenances', 'admin/provenances.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (29, 'Visualizza singola provenienza', '/admin/provenances/%', 'admin/provenances.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (30, 'Modifica provenienza', '/admin/provenances/%/edit', 'admin/provenances.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (31, 'Cancella provenienza', '/admin/provenances/%/delete', 'admin/provenances.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (32, 'Visualizza recensioni', '/admin/reviews', 'admin/reviews.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (33, 'Visualizza singola recensione', '/admin/reviews/%', 'admin/reviews.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (34, 'Modifica recensione', '/admin/reviews/%/edit', 'admin/reviews.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (35, 'Cancella recensione', '/admin/reviews/%/delete', 'admin/reviews.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (36, 'Visualizza gruppi', '/admin/groups', 'admin/groups.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (37, 'Visualizza singolo gruppo', '/admin/groups/%', 'admin/groups.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (38, 'Modifica gruppo', '/admin/groups/%/edit', 'admin/groups.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (39, 'Cancella gruppo', '/admin/groups/%/delete', 'admin/groups.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (40, 'Visualizza servizi', '/admin/services', 'admin/services.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (41, 'Visualizza singolo servizio', '/admin/services/%', 'admin/services.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (42, 'Modifica servizio', '/admin/services/%/edit', 'admin/services.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (43, 'Cancella servizio', '/admin/services/%/delete', 'admin/services.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (44, 'Visualizza immagini', '/admin/products/%/images', 'admin/images.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (45, 'Visualizza singola immagine', '/admin/products/%/images/%', 'admin/images.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (46, 'Modifica immagini', '/admin/products/%/images/edit', 'admin/images.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (47, 'Cancella immagini', '/admin/products/%/images/%/delete', 'admin/images.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (48, 'Visualizza Permessi Utenti', '/admin/permissions', 'admin/permissions.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (49, 'Modifica permessi utente', '/admin/permissions/%', 'admin/permissions.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (50, 'Aggiungi permessi utente', '/admin/permissions/%/create', 'admin/permissions.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (51, 'Cancella permessi utente', '/admin/permissions/%/delete', 'admin/permissions.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (52, 'Aggiungi prodotto', '/admin/products/create', 'admin/products.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (53, 'Aggiungi produttore', '/admin/producers/create', 'admin/producers.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (54, 'Aggiungi provenienza', '/admin/provenances/create', 'admin/provenances.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (55, 'Aggiungi gruppo', '/admin/groups/create', 'admin/groups.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (56, 'Aggiungi servizio', '/admin/services/create', 'admin/services.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (57, 'Aggiungi immagine', '/admin/products/%/images/create', 'admin/images.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (58, 'Aggiungi categoria', '/admin/categories/create', 'admin/categories.php', 'create');
