INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza home', '/', 'home.php', 'home');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza about', '/about', 'about.php', 'about');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza contact', '/contacts', 'contacts.php', 'contacts');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza login', '/login', 'auth/access.php', 'login');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Effettua logout', '/logout', 'auth/access.php', 'logout');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Effettua registrazione', '/register', 'auth/access.php', 'register');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza carrello', '/cart', 'cart.php', 'cart');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza home admin', '/admin', 'admin/index.php', 'admin');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza ordini', '/admin/orders', 'admin/orders.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singolo ordine', '/admin/orders/%', 'admin/orders.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica ordine', '/admin/orders/%/edit', 'admin/orders.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella ordine', '/admin/orders/%/delete', 'admin/orders.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza utenti', '/admin/users', 'admin/users.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singolo utente', '/admin/users/%', 'admin/users.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica utente', '/admin/users/%/edit', 'admin/users.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella utente', '/admin/users/%/delete', 'admin/users.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza prodotti', '/admin/products', 'admin/products.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singolo prodotto', '/admin/products/%', 'admin/products.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica prodotto', '/admin/products/%/edit', 'admin/products.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella prodotto', '/admin/products/%/delete', 'admin/products.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza categorie', '/admin/categories', 'admin/categories.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singola categoria', '/admin/categories/%', 'admin/categories.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica categoria', '/admin/categories/%/edit', 'admin/categories.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella categoria', '/admin/categories/%/delete', 'admin/categories.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza produttori', '/admin/producers', 'admin/producers.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singolo produttore', '/admin/producers/%', 'admin/producers.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica produttore', '/admin/producers/%/edit', 'admin/producers.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella produttore', '/admin/producers/%/delete', 'admin/producers.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza provenienze', '/admin/provenances', 'admin/provenances.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singola provenienza', '/admin/provenances/%', 'admin/provenances.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica provenienza', '/admin/provenances/%/edit', 'admin/provenances.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella provenienza', '/admin/provenances/%/delete', 'admin/provenances.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza recensioni', '/admin/reviews', 'admin/reviews.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singola recensione', '/admin/reviews/%', 'admin/reviews.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica recensione', '/admin/reviews/%/edit', 'admin/reviews.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella recensione', '/admin/reviews/%/delete', 'admin/reviews.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza gruppi', '/admin/groups', 'admin/groups.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singolo gruppo', '/admin/groups/%', 'admin/groups.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica gruppo', '/admin/groups/%/edit', 'admin/groups.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella gruppo', '/admin/groups/%/delete', 'admin/groups.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza servizi', '/admin/services', 'admin/services.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singolo servizio', '/admin/services/%', 'admin/services.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica servizio', '/admin/services/%/edit', 'admin/services.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella servizio', '/admin/services/%/delete', 'admin/services.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza immagini', '/admin/products/%/images', 'admin/images.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza singola immagine', '/admin/products/%/images/%', 'admin/images.php', 'show');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica immagini', '/admin/products/%/images/edit', 'admin/images.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella immagini', '/admin/products/%/images/%/delete', 'admin/images.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Visualizza Permessi Utenti', '/admin/permissions', 'admin/permissions.php', 'index');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Modifica permessi utente', '/admin/permissions/%', 'admin/permissions.php', 'edit');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi permessi utente', '/admin/permissions/%/create', 'admin/permissions.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Cancella permessi utente', '/admin/permissions/%/delete', 'admin/permissions.php', 'delete');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi prodotto', '/admin/products/create', 'admin/products.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi produttore', '/admin/producers/create', 'admin/producers.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi provenienza', '/admin/provenances/create', 'admin/provenances.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi gruppo', '/admin/groups/create', 'admin/groups.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi servizio', '/admin/services/create', 'admin/services.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi immagine', '/admin/products/%/images/create', 'admin/images.php', 'create');
INSERT INTO services (id, username, url, script, callback) VALUES (NULL, 'Aggiungi categoria', '/admin/categories/create', 'admin/categories.php', 'create');
